services:
  frontend:
    container_name: jobber-webapp
    build:
      context: .
      dockerfile: Dockerfile.webapp
    restart: always
    ports:
      - 4001:80
    environment:
      VITE_AUTH0_CLIENT_ID_WEB: ${VITE_AUTH0_CLIENT_ID_WEB}
      VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}

  db:
    image: postgres:16.3-bookworm
    container_name: jobber-postgres
    restart: always
    # set shared memory limit when using docker-compose (default: 128mb)
    shm_size: 265mb
    ports:
      - 5432:5432
    volumes:
      - ~/jobber/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  server:
    container_name: jobber-server
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres?schema=jobber
      CORS_WHITELIST: ${CORS_WHITELIST}
      VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
      AUTH0_CLIENT_ID_API: ${AUTH0_CLIENT_ID_API}
      AUTH0_CLIENT_SECRET_API: ${AUTH0_CLIENT_SECRET_API}
