name: Release

on:
  push:
    branches:
      - main

jobs:
  check-env:
    runs-on: self-hosted
    steps:
      - name: Check Environment Variables
        run: |
          if [ -z "${{ secrets.VITE_AUTH0_CLIENT_ID_WEB }}" ]; then
            echo "VITE_AUTH0_CLIENT_ID_WEB is not set"
            exit 1
          fi

          if [ -z "${{ secrets.VITE_AUTH0_DOMAIN }}" ]; then
            echo "VITE_AUTH0_DOMAIN is not set"
            exit 1
          fi
          if [ -z "${{ secrets.POSTGRES_PASSWORD }}" ]; then
            echo "POSTGRES_PASSWORD is not set"
            exit 1
          fi

  write-env:
    needs: check-env
    runs-on: self-hosted
    steps:
      - name: Write Environment Variables
        run: |
          echo "VITE_AUTH0_CLIENT_ID_WEB=${{ secrets.VITE_AUTH0_CLIENT_ID_WEB }}" >> .env
          echo "VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}" >> .env
          echo "DATABASE_URL=postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/postgres?schema=jobber" >> .env
      - name: Check location
        run: pwd

  deploy-database:
    needs: write-env
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy Database
        run: POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} docker compose -f postgres/docker-compose.yaml up -d

  migrate-db:
    # Node must be install on this runner
    needs: deploy-database
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        run: npm clean-install

      - name: Migrate Database
        run: npm run db:migrate

  deploy:
    needs: migrate-db
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy
        run: |
          docker compose up -d --build

  release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        run: npm clean-install

      - name: Semantic-Release
        run: npm run release
